; Performance
opcache.enable=1
opcache.revalidate_freq=0
opcache.validate_timestamps=1
opcache.max_accelerated_files=20000
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1

; APCu
apc.enable_cli=1

; Error reporting (dev)
error_reporting=E_ALL
display_errors=On
log_errors=On

; Limits
memory_limit=256M
max_execution_time=60
upload_max_filesize=20M
post_max_size=20M

; Timezone
date.timezone=UTC
